[pytest]
; addopts = --reruns 2 --reruns-delay 1
addopts = -v 
testpaths = tests
markers =
    smoke: quick sanity tests
    regression: full regression suite
    api: API tests only
    ui: UI tests only