name: Selenium Test Suite
# name of pipeline

# pipeline runs on push and pull request events to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
  # pipeline runs in latest linux env provided by GitHub Actions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    # setting up chrome nd firefox for tests as linux env does not have browsers installed by default
    - name: Setup Chrome and Firefox Browsers
      uses: browser-actions/setup-chrome@v1
    - name: Setup Firefox Browser
      uses: browser-actions/setup-firefox@v1
    # setting up python for running tests
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
      # installing dependencies from requirements.txt file
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # runs tests mapping the secrets from GitHub Actions to environment variables for use in the tests
    - name: Run tests headless
      env:
        MY_KEY: ${{ secrets.MY_KEY }}
        UI_LOGIN_USERNAME: ${{ secrets.UI_LOGIN_USERNAME }}
        UI_LOGIN_PASSWORD: ${{ secrets.UI_LOGIN_PASSWORD }}
        REQRES_EMAIL: ${{ secrets.REQRES_EMAIL }}
        REQRES_PASSWORD: ${{ secrets.REQRES_PASSWORD }}
        API_REGISTER_EMAIL: ${{ secrets.API_REGISTER_EMAIL }}
        API_REGISTER_PASSWORD: ${{ secrets.API_REGISTER_PASSWORD }}
      run: python -m pytest tests/ --headless --alluredir=reports/allure-results