name: Selenium Test Suite
# name of pipeline

# pipeline runs when someone pushes/pull req to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Grants permission to upload the website files to a new branch
permissions:
  contents: write

# jobs named as test
jobs:
  test:
  # pipelines runs on latest linux machine that github provides
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Google Chrome & Firefox for headless testing in linux so that cross browser testing logic don't crash from the project
    - name: Setup Chrome and Firefox Browsers
      uses: browser-actions/setup-chrome@v1
    - name: Setup Firefox Browser
      uses: browser-actions/setup-firefox@v1

    # Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Cache dependencies to speed up future pipeline runs
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests with ALL environment variables mapped
    - name: Run tests headless
      env:
        MY_KEY: ${{ secrets.MY_KEY }}
        LOGIN_USERNAME: ${{ secrets.UI_LOGIN_USERNAME }}
        LOGIN_PASSWORD: ${{ secrets.UI_LOGIN_PASSWORD }}
        REQRES_EMAIL: ${{ secrets.REQRES_EMAIL }}
        REQRES_PASSWORD: ${{ secrets.REQRES_PASSWORD }}
        API_REGISTER_EMAIL: ${{ secrets.API_REGISTER_EMAIL }}
        API_REGISTER_PASSWORD: ${{ secrets.API_REGISTER_PASSWORD }}
      run: python -m pytest tests/ --headless --alluredir=reports/allure-results
      # added "if: always()" to the following steps soreport builds even if a test fails
      # 1. Pulling previous test histories from gh-pages branch to build trends
    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    # 2. Compiling raw JSON results into the final static website folder
    - name: Build Allure test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_results: reports/allure-results
        allure_history: allure-history

    # 3. Publishing the generated website folder live to the web
    - name: Publish test report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history

# A pipeline is an automated sequence of steps that runs our test suite whenever code is pushed to the repository. It installs dependencies, sets up the environment and runs tests automatically without manual intervention so we catch bugs immediately when new code is merged"